refactor: logging, manually mode, args, search logic
xFuture603/helper_scripts pull request #11
Opened 2024-06-24 21:50 UTC by Nemental

2024-06-25 18:55 UTC, xFuture603 requested changes
Thank you for your work and for your pull request!

This is indeed a great upgrade for this script. I've left a few comments as a review on this pull request.

One more thing that came up while testing. I tried the default behavior of the script with iTerm2 in this example (which was manually installed in this case) and it gave me this error:

```
Checking for "iterm"...
Cask "iterm" not found. Here are some alternatives:
1. font-ia-writer-mono
2. iterm2
3. iterm2@beta
4. iterm2@nightly
5. itermai
6. therm
Choose a cask by number (1-6), or press Enter to skip: 2
You selected: iterm2
Trying to install "iterm2" with Homebrew...
Adopt installation failed for "iterm2":
Error: The bundle short version of /opt/homebrew/Caskroom/iterm2/3.5.2/iTerm.app is 3.5.2 but is 3.4.23 for /Applications/iTerm.app!
Error: It seems the existing App is different from the one being installed.
```

I think it would be nice if it tries to uninstall and reinstall the program to avoid these errors. What do you think?

2024-06-25 18:55 UTC, xFuture603 commented on brew_cask_and_adopt_manual_installed_applications/brew_cask_and_adopt_manual_installed_applications.py
> +class Colors:
Could you re-add the docstring for this class?

2024-06-25 18:55 UTC, xFuture603 commented on brew_cask_and_adopt_manual_installed_applications/brew_cask_and_adopt_manual_installed_applications.py
> +        print("For more available Homebrew Casks, visit https://formulae.brew.sh/cask/")
Could you add an empty line before this print statement? Currently, it looks a bit too cluttered IMO.

2024-06-25 18:55 UTC, xFuture603 commented on brew_cask_and_adopt_manual_installed_applications/brew_cask_and_adopt_manual_installed_applications.py
> +    parser.add_argument(
Could you also update the README.md with the new parameters please?

2024-06-26 07:51 UTC, Nemental commented
@xFuture603
> I think it would be nice if it tries to uninstall and reinstall the program to avoid these errors. What do you think?

I've already thought about this, let me take a look 👍 It sounds like a good use case for a `-u`/`--upgrade` argument. But I would leave the default behavior as it is now to avoid application conflicts?!

2024-06-26 09:00 UTC, Nemental commented
I didn't choose the way with an extra argument, instead it asks each time if the version is different from the installed one.

2024-06-26 19:50 UTC, xFuture603 commented
> he version is

Looking good now, after I've tested it again. I will merge this pull request now. Thank you!

2024-06-26 19:50 UTC, xFuture603 approved these changes

2024-06-26 19:50 UTC, merged